{
  "domain": "reqnet",
  "name": "Reqnet",
  "codeowners": ["@jarekb76"],
  "config_flow": true,
  "documentation": "https://github.com/jarekb76/HA_reqnet",
  "issue_tracker": "https://github.com/jarekb76/HA_reqnet/issues",
  "integration_type": "device",
  "iot_class": "cloud_polling",
  "requirements": [
    "requests>=2.25.1"
  ],
  "version": "1.0.0"
}