name: HACS Validation

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master
  workflow_dispatch:

jobs:
  validate:
    runs-on: ubuntu-latest
    name: Validate
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: HACS validation
        uses: hacs/action@main
        with:
          category: integration
          ignore: "brands"  # Opcjonalnie ignoruj określone błędy

      - name: Hassfest validation
        uses: home-assistant/actions/hassfest@master
